use_frameworks!

platform :ios, '9.0'

target 'KKMonitor_Example' do
  pod 'KKMonitor', :path => '../'

  target 'KKMonitor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
