use_frameworks!

platform :ios, '9.0'

target 'CxyMonitorKit_Example' do
  pod 'CxyMonitorKit', :path => '../'

  target 'CxyMonitorKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
